import { Carousel, ListGroup } from 'react-bootstrap';
import Image from 'react-bootstrap/Image';

export const StoriesBar = () => (
    <Carousel>
        <Carousel.Item>
            <ListGroup horizontal={true}>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/237/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/1003/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/1005/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/101/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/1013/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/1015/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
            </ListGroup>
        </Carousel.Item>
        <Carousel.Item>
            <ListGroup horizontal={true}>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/237/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/1003/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/1005/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/101/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/1013/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
                <ListGroup.Item>
                    <Image
                        className="w-80"
                        src="https://picsum.photos/id/1015/80/80"
                        roundedCircle={true}
                        thumbnail={true}
                    />
                </ListGroup.Item>
            </ListGroup>
        </Carousel.Item>
    </Carousel>
);
